name: Build Shared and Server

on:
    push:

permissions:
    contents: read

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  check-latest: true

            - name: create .npmrc
              run: |
                  echo "@aditya-arcot:registry=https://npm.pkg.github.com/" >> .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_NPM_TOKEN }}" >> .npmrc
                  cp .npmrc shared/
                  cp .npmrc server/

            - name: npm config
              run: npm config ls

            - name: npm cache
              run: |
                  npm cache verify
                  npm cache clean --force

            - name: install, build shared
              run: |
                  cd shared/
                  npm ci --userconfig=/dev/null
                  npm run build

            - name: install, build server
              run: |
                  cd server/
                  npm ci --userconfig=/dev/null
                  npm run build
