name: Build Shared and Server

on:
    push:

permissions:
    contents: read

jobs:
    build:
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  check-latest: true

            - name: create .npmrc
              run: |
                  echo "@aditya-arcot:registry=https://npm.pkg.github.com/" >> .npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_NPM_TOKEN }}" >> .npmrc
                  cp .npmrc shared/
                  cp .npmrc server/

            - name: npm config
              run: npm --userconfig=/dev/null config ls

            - name: npm cache
              run: |
                  npm --userconfig=/dev/null cache verify
                  npm --userconfig=/dev/null cache clean --force

            - name: install, build shared
              working-directory: shared
              run: |
                  npm --userconfig=/dev/null ci
                  npm --userconfig=/dev/null run build

            - name: install, build server
              working-directory: server
              run: |
                  npm --userconfig=/dev/null ci
                  npm --userconfig=/dev/null run build
