name: Build Shared and Server

on:
    push:

permissions:
    contents: read

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  check-latest: true

            - name: install, build shared
              run: |
                  cd shared/
                  npm ci
                  npm run build

            - name: install, build server
              run: |
                  cd server/
                  npm ci
                  npm run build
